#!/bin/sh

# usage: ./pkgdist.sh [<option>]
# <option> is any of:
# 	- a pkg file, with all dependencies in the same location
# 		(can be local, http://, https://, or ftp://)
#   - 'src'
#   - 'tests'
#   - 'ports'
#   - 'base'
#   - 'base-dbg'
#   - 'kernel'
#   - 'kernels-dbg'
#   - 'minimal'
#   - 'minimal-dbg'

if [ -z "$1" ]; then
	echo "Expected 1 or more arguments, got 0" >&2
	exit 1;
fi

tar_xz="tar -cvJf"

set -eu
trap '[ -e "${temp}" ] && rm -rf "${temp}"' EXIT

get_files() {
	temp="$1"; shift
	package="$1"; shift
	pkglist="$1"; shift
	skip_first="$1"

	for dep in $(pkg info -dq "${package}*"); do
		for old_dep in ${pkglist}; do
			if [ "${old_dep}" = "${dep}" ]; then
				continue 2
			fi
		done
		pkglist="${pkglist} ${dep}"
		get_files "${temp}" "${dep}" "${pkglist}"
	done
	if [ "${skip_first}" != "skip" ]; then
		pkg list "${package}" >> "${temp}"
	fi
}

for input_name in "$@"; do
	case ${input_name} in
		src|lib32|base-dbg|kernels-dbg|minimal|minimal-dbg)
			temp=$(mktemp) || exit 1
			get_files "${temp}" "FreeBSD-set-${input_name}"
			${tar_xz} "${input_name}.txz" -nLT "${temp}"
			;;

		ports)
			${tar_xz} ports.txz -L \
			--exclude .svn --exclude .git --exclude distfiles \
			--exclude packages --exclude INDEX* --exclude work \
			/usr/ports
			;;

		kernel)
			kern=$(pkg info -x FreeBSD-kernel | head -n 1)
			echo Making dist set from "${kern}"
			temp=$(mktemp) || exit 1
			get_files "${temp}" "${kern}" 
			${tar_xz} kernel.txz -T "${temp}"
			;;

		base)
			temp=$(mktemp) || exit 1
			get_files "${temp}" FreeBSD-set-base
			${tar_xz} base.txz -T "${temp}"
			;;

		*) # install the pkg to a temp folder and package that.
			temp=$(mktemp -d) || exit 1

			prefix=$(pwd)
			case "${input_name}" in
				"https://"*|"http://"*|"ftp://"*)
					prefix=""
					;;
				*)
					prefix="$(pwd)/"
					;;
			esac
			INSTALL_AS_USER=true ASSUME_ALWAYS_YES=true pkg -r "${temp}" add "${prefix}${input_name}"


			# remove files generated by pkg
			rm -r "${temp}/var/db/pkg"
			if [ -n "$(ls -A ${temp}/var/db || :)" ]; then
				# if there is other stuff in /var/db, this is probably base.txz,
				# which should have an empty /var/db/pkg
				mkdir "${temp}/var/db/pkg"
			else
				rm -r "${temp}/var/db"
				[ -n "$(ls -A ${temp}/var || :)" ] || rm -r "${temp}/var"
			fi
			
			# make tarball
			${tar_xz} "${input_name%pkg}txz" -C "${temp}" .
			;;
	esac
done
